/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AmbulanceWorkArea;

import Business.EcoSystem;
import Business.Emergency.Emergency;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.HospitalEmergencyWardOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.CallCenterRequestAmbulance;
import Business.utils.Check;
import Business.utils.MyStringVerifier;
import Business.utils.SpaceStringCheckVerifier;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayushi
 */
public class ProcessAmbulanceWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessAmbulanceWorkRequestJPanel
     */
    private JPanel userProcessContainer;
    private CallCenterRequestAmbulance request;
    EcoSystem business;
    private ArrayList<Enterprise> enterpriseSearch; 
    public ProcessAmbulanceWorkRequestJPanel(JPanel userProcessContainer,CallCenterRequestAmbulance request, EcoSystem business ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.business=business;
        populateNetworkCombo();
        if(request.getEmergency().getEmergencyType().getValue().equals(Emergency.EmergencyType.Fire.getValue()))
            {
            NoPatientsJTextField.setEnabled(true);
            }
            else{
             NoPatientsJTextField.setEnabled(false);
            }
        
        MyStringVerifier myStringVerifier= new MyStringVerifier();
        searchIDJTextField.setInputVerifier(myStringVerifier);
        Check chk = new Check();
        NoPatientsJTextField.setInputVerifier(chk);
        SpaceStringCheckVerifier spacecheck= new SpaceStringCheckVerifier();
        resultJTextField.setInputVerifier(spacecheck);

    }
    

    public void populateNetworkCombo(){
        stateJCombo.removeAllItems();
        for(Network ntw: business.getNetworkList())
        {
            stateJCombo.addItem(ntw);
        }
       
    
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        stateJCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        htable = new javax.swing.JTable();
        searchIDJTextField = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NoPatientsJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(154, 192, 205));

        submitJButton.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        submitJButton.setText("Submit Result");
        submitJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        jLabel1.setText("Message to Emergency Ward");

        backJButton.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel2.setText("Process Request to Hospital");

        stateJCombo.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        stateJCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stateJCombo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stateJCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateJComboActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        jLabel3.setText("State To Choose Hospital");

        htable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        htable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital Name", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(htable);

        search.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        search.setText("Search >>");
        search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        jLabel4.setText("No Of Patients");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchIDJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stateJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NoPatientsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(resultJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NoPatientsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(submitJButton))
                .addGap(121, 121, 121))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        Organization org = null;
//        int noPatient= Integer.parseInt(NoPatientsJTextField.getText().trim());
        if (resultJTextField.getText().length()==0)
        {
           JOptionPane.showMessageDialog(null, "Please Enter message", "Error", JOptionPane.ERROR_MESSAGE);
           return;
 
        }
        int selectedRow = htable.getSelectedRow();
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select row","Warning", JOptionPane.WARNING_MESSAGE);
            }
        else{
           Enterprise enterprise = (Enterprise) htable.getValueAt(selectedRow, 0);
           for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof HospitalEmergencyWardOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            request.setAmbulanceMessage(resultJTextField.getText());
            request.setStatusAmbulance("Completed");
            request.setStatusEmergency("Sent");
             Date date = new Date();
             request.setResolveDate(date);
            if(request.getEmergency().getEmergencyType().getValue().equals(Emergency.EmergencyType.Fire.getValue()))
            {
            request.setNoofPatients(Integer.parseInt(NoPatientsJTextField.getText().trim()));
            }
            else{
             request.setNoofPatients(1);   
            }
            JOptionPane.showMessageDialog(null,"Request has been successfully sent to Emergency Ward");
        }
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AmbulanceWorkAreaJPanel ajp = (AmbulanceWorkAreaJPanel) component;
        ajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void stateJComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateJComboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_stateJComboActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        enterpriseSearch = new ArrayList<>();
        Network network = (Network)stateJCombo.getSelectedItem();
        String id = searchIDJTextField.getText().trim();
        if(network==null)
        {
            JOptionPane.showMessageDialog(null, "Please Select a state to look for hospitals");
            return;
        }
        
            for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){
               
                if(enterprise instanceof HospitalEnterprise){
                    System.out.println("Enterprise Location: enterprise.getLocation() "+enterprise.getLocation());
                    System.out.println("enterprise.getEnterpriseType().getValue() :"+ enterprise.getEnterpriseType().getValue());
                    System.out.println("id :"+id);
                    if(enterprise.getLocation().equals(id)){
                        System.out.println("Inside if(enterprise.getLocation().equals(id))");
                        enterpriseSearch.add(enterprise);
                         System.out.println("added");
            
                    }
                }
            }
            
          
            
         DefaultTableModel model = (DefaultTableModel) htable.getModel();
         model.setRowCount(0);
         for (Enterprise e : enterpriseSearch){
              Object[] row = new Object[3];
                row[0] = e;
                row[1] = e.getName();
                row[2] = e.getLocation();
                model.addRow(row);
         }
            
    }//GEN-LAST:event_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NoPatientsJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTable htable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchIDJTextField;
    private javax.swing.JComboBox stateJCombo;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
