/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorWorkArea;

import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ayushi
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organization=(DoctorOrganization) organization;
        this.userAccount=account;
        this.enterprise = enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewEmergency = new javax.swing.JButton();
        ManagePatients = new javax.swing.JButton();
        CreateRequest = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel1.setText("Doctor Work Area");
        add(jLabel1);
        jLabel1.setBounds(120, 60, 180, 23);

        viewEmergency.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        viewEmergency.setText("View Emergency Requests");
        viewEmergency.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmergencyActionPerformed(evt);
            }
        });
        add(viewEmergency);
        viewEmergency.setBounds(350, 130, 230, 29);

        ManagePatients.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        ManagePatients.setText("Manage My Patients");
        ManagePatients.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ManagePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagePatientsActionPerformed(evt);
            }
        });
        add(ManagePatients);
        ManagePatients.setBounds(350, 200, 230, 29);

        CreateRequest.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        CreateRequest.setText("Create Requests to Nurse");
        CreateRequest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreateRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateRequestActionPerformed(evt);
            }
        });
        add(CreateRequest);
        CreateRequest.setBounds(350, 280, 230, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/DoctorWorkArea/23420-200.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(60, 130, 210, 210);
    }// </editor-fold>//GEN-END:initComponents

    private void viewEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmergencyActionPerformed
        // TODO add your handling code here:
        ViewDoctorRequestWorkAreaJPanel vdr = new ViewDoctorRequestWorkAreaJPanel(userProcessContainer, userAccount, organization, enterprise);
        userProcessContainer.add("ViewDoctorRequestWorkAreaJPanel", vdr);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewEmergencyActionPerformed

    private void ManagePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagePatientsActionPerformed
        // TODO add your handling code here:
        ViewPatientsWorkAreaJPanel vp = new ViewPatientsWorkAreaJPanel(userProcessContainer, userAccount, organization, enterprise);
        userProcessContainer.add("ViewPatientsWorkAreaJPanel", vp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManagePatientsActionPerformed

    private void CreateRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateRequestActionPerformed
        // TODO add your handling code here:
        CreateRequestNurseWorkAreaJPanel cnp = new CreateRequestNurseWorkAreaJPanel(userProcessContainer, userAccount, organization, enterprise);
        userProcessContainer.add("CreateRequestNurse", cnp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_CreateRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateRequest;
    private javax.swing.JButton ManagePatients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton viewEmergency;
    // End of variables declaration//GEN-END:variables
}
