/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CallCenterWorkArea;

import Business.Enterprise.Enterprise;
import Business.Organization.FccCallCenterOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ayushi
 */
public class CallCenterMainWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CallCenterMainWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private FccCallCenterOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public CallCenterMainWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (FccCallCenterOrganization) organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RequestMedCrimEmergency = new javax.swing.JButton();
        carEmergency = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        RequestMedCrimEmergency.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        RequestMedCrimEmergency.setText("Request for Medical and Criminal Emergencies");
        RequestMedCrimEmergency.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RequestMedCrimEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestMedCrimEmergencyActionPerformed(evt);
            }
        });
        add(RequestMedCrimEmergency);
        RequestMedCrimEmergency.setBounds(93, 240, 370, 29);

        carEmergency.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        carEmergency.setText("Request for Car Accidents Emergencies");
        carEmergency.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        carEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carEmergencyActionPerformed(evt);
            }
        });
        add(carEmergency);
        carEmergency.setBounds(100, 320, 360, 29);

        enterpriseLabel.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(100, 120, 127, 30);

        valueLabel.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel);
        valueLabel.setBounds(240, 120, 158, 26);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel1.setText("CallCenter Employee Work Area");
        add(jLabel1);
        jLabel1.setBounds(100, 50, 238, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CallCenterWorkArea/emergency-call.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(460, 40, 320, 240);
    }// </editor-fold>//GEN-END:initComponents

    private void RequestMedCrimEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestMedCrimEmergencyActionPerformed
        // TODO add your handling code here:
            RequestCrimeMedicalWorkAreaJPanel rWorkRequestJPanel = new RequestCrimeMedicalWorkAreaJPanel(userProcessContainer,userAccount, organization, enterprise);
            userProcessContainer.add("processWorkRequestJPanel", rWorkRequestJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_RequestMedCrimEmergencyActionPerformed

    private void carEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carEmergencyActionPerformed
        // TODO add your handling code here:
            RequestCarWorkAreaJPanel cWorkRequestJPanel = new RequestCarWorkAreaJPanel(userProcessContainer,userAccount, organization, enterprise);
            userProcessContainer.add("processWorkRequestJPanel", cWorkRequestJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        
    }//GEN-LAST:event_carEmergencyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestMedCrimEmergency;
    private javax.swing.JButton carEmergency;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
