/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NurseWorkArea;

import Business.Patient.Medication;
import Business.Patient.Patient;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.draw.LineSeparator;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayushi
 */
public class ViewBillJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewBillJPanel
     */
    private JPanel userProcessContainer;
    private Patient patient;

    public ViewBillJPanel(JPanel userProcessContainer, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;

        PatientNameJTextField.setEnabled(false);
        PatientNameJTextField.setBackground(Color.WHITE);
        hospitalfees.setEditable(false);
        amountJTextField.setEditable(false);
        hospitalfees.setText("500");
        PatientNameJTextField.setText(patient.getPatientName());
        PatientNameJTextField.setEditable(false);
        populate();
    }

    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) billJTable.getModel();
        dtm.setRowCount(0);
        int total = 0;
        for (Medication med : patient.getMedicationDirectory().getMedicationList()) {
            Object[] row = new Object[3];
            row[0] = med.getMedication_type();
            row[1] = med.getMedication_description();
            row[2] = med.getCost();
            total += med.getCost();
            dtm.addRow(row);
        }
        int amt = 500 + total;
        patient.setTotal(amt);
        amountJTextField.setText(String.valueOf(amt));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billJTable = new javax.swing.JTable();
        PatientNameJTextField = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        generatePDF = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hospitalfees = new javax.swing.JTextField();
        amountJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(154, 192, 205));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel1.setText("Hospital Bill");

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        jLabel2.setText("Patient Name");

        billJTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        billJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medication Type", "Description", "Cost"
            }
        ));
        jScrollPane1.setViewportView(billJTable);
        if (billJTable.getColumnModel().getColumnCount() > 0) {
            billJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        back.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        back.setText("<<Back");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        generatePDF.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        generatePDF.setText("Generate Bill PDF");
        generatePDF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generatePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePDFActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bill Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 15))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        jLabel4.setText("Hospital Fees");

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        jLabel3.setText("Total Amount Due");

        jLabel5.setText("$");

        jLabel6.setText("$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(amountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hospitalfees, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hospitalfees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(amountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(PatientNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(back)
                                .addGap(82, 82, 82)
                                .addComponent(generatePDF)
                                .addGap(36, 36, 36))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generatePDF)
                    .addComponent(back))
                .addGap(92, 92, 92))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backActionPerformed

    private void generatePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePDFActionPerformed
        try {
            // TODO add your handling code here:
            Document doc = new Document();
            try {
                PdfWriter pdfWriter = PdfWriter.getInstance(doc, new FileOutputStream(patient.getPatientName() + ".pdf"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ViewBillJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DocumentException ex) {
                Logger.getLogger(ViewBillJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            doc.open();
            Paragraph paragraph1 = new Paragraph();
            paragraph1.add("HOSPITAL BILL");
            paragraph1.setAlignment(Element.ALIGN_CENTER);
            doc.add(paragraph1);
            doc.add(Chunk.NEWLINE);
            doc.add(new LineSeparator());
            doc.add(Chunk.NEWLINE);
            doc.add(Chunk.NEWLINE);
            Paragraph paragraph2 = new Paragraph();
            paragraph2.add("Patient Name : " + patient.getPatientName());
            paragraph2.setAlignment(Element.ALIGN_LEFT);
            doc.add(paragraph2);
            doc.add(Chunk.NEWLINE);
            Paragraph paragraph3 = new Paragraph();
            paragraph3.add("Patient Room : " + patient.getRoom_no());
            paragraph3.setAlignment(Element.ALIGN_LEFT);
            doc.add(paragraph3);
            doc.add(Chunk.NEWLINE);
            doc.add(Chunk.NEWLINE);
            PdfPTable table = new PdfPTable(3);

            PdfPCell cell;

            cell = new PdfPCell(new Phrase("Patient Bill Details"));
            cell.setColspan(3);
            table.addCell(cell);
          
            table.addCell("Medication Type");
            table.addCell("Description");
            table.addCell("Price");
            
            for(Medication med : patient.getMedicationDirectory().getMedicationList()){
                table.addCell(med.getMedication_description());
                table.addCell(med.getMedication_description());
                table.addCell(String.valueOf(med.getCost()));
            }
            
            cell = new PdfPCell(new Phrase("Hospital fees"));
            cell.setColspan(2);
            table.addCell(cell);
            table.addCell("500");
            cell = new PdfPCell(new Phrase("Total Amount"));
            cell.setColspan(2);
            table.addCell(cell);
            table.addCell(String.valueOf(patient.getTotal()));
             doc.add(table);
            doc.add(Chunk.NEWLINE);
            doc.add(Chunk.NEWLINE);
            
            Paragraph paragraph4 = new Paragraph();
            paragraph4.add("Thankyou for choosing our hospitalfor your healthcare needs. We have billed your Insurance and the balance due is your responsibility."
                    + "Please contact our customer care department at (857) 800-3978 with any questions or to set your payments. Thank you ");
            paragraph4.setAlignment(Element.ALIGN_JUSTIFIED);
            doc.add(paragraph4);
            
            
            
            doc.close();
            JOptionPane.showMessageDialog(null, "PDF Generated plese check the path to find the document", "Information", JOptionPane.INFORMATION_MESSAGE);

        } catch (DocumentException ex) {
            Logger.getLogger(ViewBillJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_generatePDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PatientNameJTextField;
    private javax.swing.JTextField amountJTextField;
    private javax.swing.JButton back;
    private javax.swing.JTable billJTable;
    private javax.swing.JButton generatePDF;
    private javax.swing.JTextField hospitalfees;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
